# Generated by Django 4.2.1 on 2023-06-23 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('is_college_amabassador', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('is_email_verified', models.BooleanField()),
                ('profile_picture', models.ImageField(null=True, upload_to='profpictures')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
