# Generated by Django 4.2.1 on 2023-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='is_req',
            field=models.BooleanField(default=True),
        ),
    ]
