# Generated by Django 4.2.1 on 2023-06-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userdetails_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
