# Generated by Django 4.2.1 on 2023-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
