# Generated by Django 4.2.1 on 2023-06-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='posted_date',
            field=models.DateField(auto_now=True, verbose_name='startdate(mm/dd/yyyy)'),
        ),
    ]
